name: Deploy to NuxtHub
on: push

jobs:
  deploy:
    name: "Deploy to NuxtHub"
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
      url: ${{ steps.deploy.outputs.deployment-url }}
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build & Deploy to NuxtHub
        uses: nuxt-hub/action@v2
        with:
          build-command: bun run build

      - name: Migrate
        run: bun --bun drizzle-kit migrate
        env:
          NUXT_DATABASE_URL: ${{ secrets.NUXT_DATABASE_URL }}
